/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103077-gf7958d0883-20210726"
#endif /* AVUTIL_FFVERSION_H */
